x-airflow-common: 
  &airflow-common
  build:
    context: .
    dockerfile: docker/Dockerfile
  env_file:
    - .env
  environment:
    PYTHONPATH: /opt/airflow/src
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${AIRFLOW_DB}
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./data:/opt/airflow/data
    - ./sql:/opt/airflow/sql
    - airflow_logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # POSTGRES_DB: ${POSTGRES_DB}AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username ${AIRFLOW_ADMIN_USERNAME}
      --password ${AIRFLOW_ADMIN_PASSWORD}
      --firstname Airflow
      --lastname Admin
      --role Admin
      --email ${AIRFLOW_ADMIN_EMAIL}
      "

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    restart: unless-stopped
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    restart: unless-stopped
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase.db
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:
  airflow_logs:
  metabase_data: